
name: Tetse


on:
  push:
    branches: [ testeusuarios ]
  pull_request:
    branches: [ testeusuarios ]

  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies and test
        run: |
          yarn --frozen-lockfile
          yarn lint
          yarn test
